application:
  subdomain: watchcat
  background_task: true
  multi_instance: false
  routes:
    - /=http://watchcat:8080
  health_check:
    test_url: http://watchcat:8080/api/v1/health
    start_period: 600s
    timeout: 10s

services:
  watchcat:
    image: registry.cn-shanghai.aliyuncs.com/wtjking/lazycat-watchcat@sha256:529a58e1aa0a117d462b5081d3644f4a001cabe5164eb1335415fdc03cf0786f
    environment:
      - WATCHCAT_ADDR=:8080
      - WATCHCAT_COLLECTOR_ADDR=:8443
      - WATCHCAT_DATA_DIR=/lzcapp/var/data
      - WATCHCAT_WEB_DIR=/opt/watchcat/web
      - WATCHCAT_DOCKER_STATS_BATCH_SIZE=8
      - WATCHCAT_DOCKER_STATS_CONCURRENCY=1
    healthcheck:
      test: ["CMD", "wget", "-q", "-T", "3", "-O", "/dev/null", "http://127.0.0.1:8080/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 600s
ext_config:
  permissions:
    - PERM_LZC_DOCKER_ADMIN
