const navs=[['overview','⌂','总览'],['devices','▦','设备'],['apps','◇','应用'],['storage','▤','存储健康'],['alerts','!','告警'],['inspections','✓','巡检'],['settings','⚙','设置']];
const titles={overview:['Fleet Overview','全部设备 · 实时健康与风险'],devices:['设备','实时设备状态与指标'],apps:['应用','跨设备 LPK 健康与版本'],storage:['存储健康','文件系统、Btrfs 与物理磁盘风险'],alerts:['告警','持久化状态、确认、静默与恢复'],inspections:['巡检报告','正式巡检记录与证据摘要'],settings:['设置','设备接入、数据保留与通知']};
const state={page:'overview',timer:null,request:0};
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';const ago=t=>{if(!t||new Date(t).getUTCFullYear()<2000)return'尚无数据';const s=Math.max(0,(Date.now()-new Date(t))/1000);if(s<60)return`${Math.round(s)} 秒前`;if(s<3600)return`${Math.round(s/60)} 分钟前`;if(s<86400)return`${Math.round(s/3600)} 小时前`;return`${Math.round(s/86400)} 天前`};
const metric=(d,name)=>d?.latest?.[name]?.[0];const val=(d,name,digits=1)=>{const m=metric(d,name);return m?`${fmt(m.value,digits)}${m.unit||''}`:'—'};
const pill=s=>`<span class="pill ${s==='critical'?'critical':s==='warning'?'warning':s==='offline'||s==='revoked'?'offline':''}">${esc(({critical:'Critical',warning:'Warning',healthy:'Healthy',offline:'Offline',revoked:'Revoked'})[s]||s)}</span>`;
const card=(a,b,c,k='')=>`<div class="card stat"><label>${esc(a)}</label><strong>${esc(b)}</strong><small class="${k}">${esc(c)}</small></div>`;
const empty=(title,text)=>`<div class="card empty"><h2>${esc(title)}</h2><p class="muted">${esc(text)}</p></div>`;
async function api(path,options){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){let message=`HTTP ${r.status}`;try{message=(await r.json()).error?.message||message}catch{}throw new Error(message)}return r.json()}
function shell(page){$('#nav').innerHTML=navs.map(n=>`<button class="nav-item ${n[0]===page?'active':''}" data-page="${n[0]}"><span>${n[1]}</span>${n[2]}</button>`).join('');$('#title').textContent=titles[page][0];$('#subtitle').textContent=titles[page][1];document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>navigate(x.dataset.page));}
function navigate(page){state.page=page;location.hash=page;shell(page);load(page);}
async function load(page){clearTimeout(state.timer);const request=++state.request;$('#content').innerHTML='<div class="card loading">正在读取实时数据…</div>';try{const html=await renderers[page]();if(request!==state.request)return;$('#content').innerHTML=html;bind(page)}catch(e){if(request!==state.request)return;$('#content').innerHTML=empty('数据加载失败',e.message)}state.timer=setTimeout(()=>{if(state.page===page)load(page)},30000)}
const renderers={
 overview:async()=>{const d=await api('/api/v1/overview'),s=d.stats||{},devices=d.devices||[],alerts=d.alerts||[];return `<div class="stats">${card('设备',s.devices??0,'已注册')}${card('在线',s.online??0,'90 秒内上报','green')}${card('离线',s.offline??0,'需要检查','amber')}${card('Critical',s.critical??0,'实时阈值','red')}${card('Warning',s.warning??0,'实时阈值','amber')}${card('健康',s.healthy??0,`更新 ${ago(d.updatedAt)}`,'green')}</div><div class="grid"><div class="card"><div class="section-title"><div><h2>设备健康矩阵</h2><span class="muted">来自 Collector 的最新真实指标</span></div></div>${devices.length?deviceTable(devices):'<p class="muted">尚未接入设备，请前往设置生成配对码。</p>'}</div><div><div class="card"><h2>当前风险</h2><p class="muted">${alerts.length} 条活动风险</p>${alerts.length?alerts.slice(0,8).map(alertRow).join(''):'<p class="green">当前没有达到阈值的风险。</p>'}</div><div class="card card-spaced"><h2>数据新鲜度</h2><p class="muted">最近一次采集：${esc(ago(d.updatedAt))}</p><p>页面每 30 秒自动刷新。过期和离线设备不会被显示为健康。</p></div></div></div>`},
 devices:async()=>{const d=await api('/api/v1/overview'),items=d.devices||[];return `<div class="page-head"><div><h2>设备清单</h2><span class="muted">${items.length} / 100 台已接入</span></div><button data-page="settings">＋ 接入设备</button></div><div class="card">${items.length?deviceTable(items,true):'<p class="muted">尚未接入设备。</p>'}</div>`},
 apps:async()=>{const d=await api('/api/v1/applications'),items=d.items||[];const instances=items.reduce((n,a)=>n+a.instances,0),healthy=items.reduce((n,a)=>n+a.healthy,0),bad=instances-healthy;return `<div class="stats">${card('LPK 应用',items.length,'已发现')}${card('设备实例',instances,'实时采集')}${card('运行正常',healthy,instances?`${fmt(healthy/instances*100)}%`:'无数据','green')}${card('异常',bad,'需要关注',bad?'amber':'green')}</div>${items.length?`<div class="card"><h2>应用矩阵</h2><table><thead><tr><th>应用</th><th>实例</th><th>正常</th><th>异常</th><th>版本</th></tr></thead><tbody>${items.map(a=>`<tr><td><b>${esc(a.id)}</b></td><td>${a.instances}</td><td class="green">${a.healthy}</td><td class="${a.unhealthy?'red':''}">${a.unhealthy}</td><td>${esc(Object.entries(a.versions||{}).map(([v,n])=>`${v||'未知'} × ${n}`).join(' · '))}</td></tr>`).join('')}</tbody></table></div>`:empty('尚无应用数据','Collector 尚未获得 LazyCat Runtime 应用状态，或设备还未上报。')}`},
 storage:async()=>{const d=await api('/api/v1/storage'),items=d.items||[],byDevice=group(items,x=>x.deviceId);return items.length?`<div class="page-head"><div><h2>Fleet 存储健康</h2><span class="muted">${items.length} 项实时存储指标 · 更新 ${ago(d.updatedAt)}</span></div></div><div class="storage-grid">${Object.values(byDevice).map(list=>storageCard(list)).join('')}</div>`:empty('尚无存储数据','基础文件系统指标会自动上报；SMART 与 Btrfs 需要对应工具及只读权限。')},
 alerts:async()=>{const d=await api('/api/v1/alerts'),items=d.items||[];return `<div class="page-head"><div><h2>告警中心</h2><span class="muted">持久化状态机 · 新发/升级/恢复通过 LazyCat 系统通知</span></div></div>${items.length?`<div class="card alert-list">${items.map(alertRow).join('')}</div>`:empty('没有活动告警','当前设备均未达到告警阈值。')}`},
 inspections:async()=>{const d=await api('/api/v1/inspections'),items=d.items||[],latest=items[0];return `<div class="page-head"><div><h2>正式巡检</h2><span class="muted">每次报告固化 Collector 快照并生成 SHA-256 证据摘要</span></div><button id="start-inspection">开始巡检</button></div>${latest?`<div class="stats">${card('检查设备',latest.deviceCount,'最近一次')}${card('健康',latest.healthyCount,'通过','green')}${card('Warning',latest.warningCount,'需关注','amber')}${card('Critical',latest.criticalCount,'需处理','red')}</div>`:''}${items.length?`<div class="card"><h2>巡检历史</h2><table><thead><tr><th>时间</th><th>设备</th><th>健康</th><th>Warning</th><th>Critical</th><th>证据 SHA-256</th></tr></thead><tbody>${items.map(i=>`<tr><td>${new Date(i.startedAt).toLocaleString()}</td><td>${i.deviceCount}</td><td class="green">${i.healthyCount}</td><td class="amber">${i.warningCount}</td><td class="red">${i.criticalCount}</td><td><code>${esc((i.evidenceSha256||'').slice(0,16))}…</code></td></tr>`).join('')}</tbody></table></div>`:empty('尚无巡检记录','点击“开始巡检”创建第一份正式报告。')}`},
 settings:async()=>{const d=await api('/api/v1/settings');return `<div class="page-head"><div><h2>设置</h2><span class="muted">生产配置来自 Hub</span></div></div><div class="tabbar"><span class="tab active">部署</span><span class="tab">数据保留</span><span class="tab">通知渠道</span></div><div class="two"><div class="card"><h2>单 LPK 部署</h2><p class="green">本机 Collector 已内置，安装“猫眼”后会自动注册当前 LazyCat 设备，无需安装第二个应用。</p><hr><h2>远端设备接入（高级）</h2><p class="muted">仅在未来接入其他设备时使用。配对码有效期 10 分钟且仅可使用一次。</p><h1 id="pairing-code" class="pairing-code">尚未生成</h1><button id="generate-code">生成配对码</button> <button id="copy" class="ghost">复制</button></div><div class="card"><h2>生产参数</h2>${setting('部署模式',d.deploymentMode==='single-lpk'?'单一 LPK':'未知')}${setting('本机采集',d.embeddedCollector?'已内置':'未启用')}${setting('用户模式',d.singleUser?'单用户':'多用户')}${setting('最大设备数',d.maxDevices)}${setting('基础采集',`${d.collectIntervalSeconds} 秒`)}${setting('高级采集',`${d.advancedIntervalSeconds} 秒`)}${setting('原始数据',`${d.rawRetentionDays} 天`)}${setting('降采样数据',`${d.rollupRetentionDays} 天`)}${setting('通知渠道',d.notificationChannel==='lazycat'?'LazyCat 系统通知':d.notificationChannel)}${setting('通知投递',d.notificationDelivery==='outbox-retry'?'持久队列重试':d.notificationDelivery)}${setting('原始指标行',d.storageStats?.rawMetricRows??0)}${setting('小时降采样行',d.storageStats?.rollupRows??0)}${setting('待发送通知',d.storageStats?.pendingNotifications??0)}</div></div>`}
};
function deviceTable(items,clickable=false){return `<table><thead><tr><th>设备</th><th>CPU/负载</th><th>内存</th><th>存储</th><th>最后上报</th><th>状态</th></tr></thead><tbody>${items.map(d=>`<tr ${clickable?`class="device-row" data-device="${esc(d.id)}"`:''}><td class="device"><b>${esc(d.name)}</b><small>${esc(d.hostname)} · ${esc(d.osVersion||'系统版本未知')}</small></td><td>${val(d,'system.load.1m',2)}</td><td>${val(d,'system.memory.usage')}</td><td>${val(d,'filesystem.root.usage')}</td><td>${ago(d.lastSeenAt)}${d.stale?' · 数据过期':''}</td><td>${pill(d.status==='revoked'?'revoked':d.online?d.health:'offline')}</td></tr>`).join('')}</tbody></table>`}
function alertRow(a){const actions=a.status==='resolved'?'':`<span class="alert-actions"><button class="tiny ghost" data-alert-action="acknowledge" data-fingerprint="${esc(a.fingerprint)}">确认</button><button class="tiny ghost" data-alert-action="silence" data-fingerprint="${esc(a.fingerprint)}">静默 24h</button><button class="tiny ghost" data-alert-action="resolve" data-fingerprint="${esc(a.fingerprint)}">解决</button></span>`;return `<div class="risk"><b>${pill(a.severity)} ${esc(a.deviceName)} · ${esc(a.resource)}<span>${esc(({firing:'触发中',acknowledged:'已确认',silenced:'已静默',resolved:'已恢复'})[a.status]||a.status)} · ${ago(a.lastSeenAt||a.observedAt||a.collectedAt)}</span></b><p>${esc(a.message)}${a.unit?` · ${fmt(a.value)}${esc(a.unit)}`:''}</p>${actions}</div>`}
function storageCard(list){const first=list[0],usage=list.find(x=>x.name.endsWith('.usage')),temp=list.find(x=>x.name==='disk.temperature'),errors=list.find(x=>x.name==='disk.nvme.media_errors');return `<div class="card"><h2>${esc(first.deviceName)}</h2><p class="muted">${esc(first.labels?.mount||first.labels?.device||'系统存储')}</p>${usage?metricLine('使用率',`${fmt(usage.value)}${usage.unit}`):''}${temp?metricLine('温度',`${fmt(temp.value,0)}°C`):''}${errors?metricLine('Media Errors',fmt(errors.value,0),errors.value?'red':'green'):''}<p class="muted">更新 ${ago(first.collectedAt)}</p></div>`}
function metricLine(k,v,c=''){return `<div class="risk"><b>${esc(k)}<span class="${c}">${esc(v)}</span></b></div>`}function setting(k,v){return metricLine(k,v)}function group(items,key){return items.reduce((m,x)=>((m[key(x)]??=[]).push(x),m),{})}
function bind(page){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>navigate(x.dataset.page));document.querySelectorAll('.device-row').forEach(x=>x.onclick=()=>showDevice(x.dataset.device));$('#refresh')?.addEventListener('click',()=>load(page));$('#start-inspection')?.addEventListener('click',startInspection);document.querySelectorAll('[data-alert-action]').forEach(x=>x.onclick=()=>alertAction(x.dataset.fingerprint,x.dataset.alertAction));$('#generate-code')?.addEventListener('click',generatePairingCode);$('#copy')?.addEventListener('click',()=>{const code=$('#pairing-code')?.textContent;if(code&&code!=='尚未生成'){navigator.clipboard?.writeText(code);toast('配对码已复制')}})}
async function showDevice(id){clearTimeout(state.timer);$('#content').innerHTML='<div class="card loading">正在读取设备详情…</div>';try{const d=await api(`/api/v1/devices/${encodeURIComponent(id)}`);$('#title').textContent=d.name;$('#subtitle').textContent=`${d.hostname} · ${d.collectorVersion}`;const metrics=Object.entries(d.latest||{}).flatMap(([,v])=>v);$('#content').innerHTML=`<div class="page-head"><div><h2>${esc(d.name)}</h2><span class="muted">最后上报 ${ago(d.lastSeenAt)}</span></div>${pill(d.online?d.health:'offline')}</div><div class="stats">${card('负载',val(d,'system.load.1m',2),'1 分钟')}${card('内存',val(d,'system.memory.usage'),'实时')}${card('根文件系统',val(d,'filesystem.root.usage'),'实时')}${card('Uptime',val(d,'system.uptime',0),'秒')}</div><div class="card"><h2>最新指标</h2>${metrics.length?`<table><thead><tr><th>指标</th><th>值</th><th>标签</th><th>采集时间</th></tr></thead><tbody>${metrics.map(m=>`<tr><td>${esc(m.name)}</td><td>${fmt(m.value)}${esc(m.unit)}</td><td>${esc(Object.entries(m.labels||{}).map(([k,v])=>`${k}=${v}`).join(', '))}</td><td>${ago(m.collectedAt)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">尚未收到指标。</p>'}</div>`}catch(e){$('#content').innerHTML=empty('设备详情加载失败',e.message)}}
async function startInspection(){const b=$('#start-inspection');if(b){b.disabled=true;b.textContent='巡检中…'}try{await api('/api/v1/inspections',{method:'POST'});toast('正式巡检已完成并保存');load('inspections')}catch(e){toast(e.message);if(b){b.disabled=false;b.textContent='重试巡检'}}}
async function alertAction(fingerprint,action){try{await api(`/api/v1/alerts/${encodeURIComponent(fingerprint)}/${action}`,{method:'POST',body:action==='silence'?JSON.stringify({durationMinutes:1440}):undefined});toast('告警状态已更新');load('alerts')}catch(e){toast(e.message)}}
async function generatePairingCode(){const b=$('#generate-code');b.disabled=true;b.textContent='生成中…';try{const d=await api('/api/v1/pairing-codes',{method:'POST'});$('#pairing-code').textContent=d.code;$('#pairing-expiry').textContent=`有效期至 ${new Date(d.expiresAt).toLocaleTimeString()} · 使用后立即失效`;b.textContent='生成新的配对码';toast('已生成一次性配对码')}catch(e){b.textContent='重试';toast(e.message)}finally{b.disabled=false}}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
$('#inspect').onclick=()=>navigate('inspections');navigate(renderers[location.hash.slice(1)]?location.hash.slice(1):'overview');
