const navs=[['overview','⌂','总览'],['devices','▦','设备'],['apps','◇','应用'],['storage','▤','存储健康'],['alerts','!','告警'],['inspections','✓','巡检'],['settings','⚙','设置']];
const devices=[['猫盒-01','机房 A · 18 秒前','32%','61%','92%','Critical'],['猫盒-02','机房 A · 21 秒前','87%','73%','68%','Warning'],['猫盒-03','工作室 · 2 分钟前','44%','82%','78%','Warning'],['猫盒-07','仓库 · 26 秒前','26%','58%','71%','Critical'],['猫盒-12','工作室 · 35 秒前','18%','47%','65%','Warning'],['猫盒-04','家庭组 · 19 秒前','21%','49%','54%','Healthy'],['猫盒-05','家庭组 · 32 秒前','16%','45%','62%','Healthy'],['猫盒-09','机房 B · 8 分钟前','—','—','—','Offline']];
const pill=s=>`<span class="pill ${s==='Critical'?'critical':s==='Warning'?'warning':s==='Offline'?'offline':''}">${s}</span>`;
const stat=(a,b,c,k='')=>`<div class="card stat"><label>${a}</label><strong>${b}</strong><small class="${k}">${c}</small></div>`;
const table=(rows=devices)=>`<table><thead><tr><th>设备</th><th>CPU</th><th>内存</th><th>存储</th><th>健康</th></tr></thead><tbody>${rows.map(d=>`<tr><td class="device"><b>${d[0]}</b><small>${d[1]}</small></td><td class="metric">${d[2]}</td><td>${d[3]}</td><td>${d[4]}</td><td>${pill(d[5])}</td></tr>`).join('')}</tbody></table>`;
const pages={
overview:()=>`<div class="stats">${stat('设备','16','4 个设备组')}${stat('在线','14','87.5%','green')}${stat('离线','2','需要检查','amber')}${stat('Critical','1','较昨日 +1','red')}${stat('Warning','4','较昨日 -2','amber')}${stat('存储风险','3','最短 6 天写满','amber')}</div><div class="grid"><div class="card"><div class="section-title"><div><h2>设备健康矩阵</h2><span class="muted">按严重程度排序 · 数据每 30 秒更新</span></div><span class="pill blue">所有设备</span></div>${table()}</div><div><div class="card"><div class="section-title"><div><h2>当前风险</h2><span class="muted">5 条待处理</span></div></div>${[['猫盒-01 · nvme0n1','Media Errors 增加','3 分钟','red'],['猫盒-07 · 相册','连续健康检查失败','8 分钟','red'],['猫盒-03 · 数据盘','预计 6 天后写满','12 分钟','amber'],['猫盒-12 · 网络','丢包率 4.2%','18 分钟','amber']].map(x=>`<div class="risk"><b>${x[0]}<span class="${x[3]}">${x[2]}</span></b><p>${x[1]}</p></div>`).join('')}</div><div class="card" style="margin-top:16px"><h2>健康趋势</h2><span class="muted">最近 24 小时</span><svg viewBox="0 0 320 110" width="100%"><path d="M0 77 C45 70 60 24 105 48 S165 88 205 53 S265 22 320 38" fill="none" stroke="#2563eb" stroke-width="3"/><path d="M0 92H320M0 60H320M0 28H320" stroke="#edf2f7"/></svg></div></div></div>`,
devices:()=>`<div class="page-head"><div><h2>设备清单</h2><span class="muted">集中查看在线状态、系统版本、资源压力与应用异常。</span></div><button>＋ 接入设备</button></div><div class="card"><div class="filters"><input placeholder="搜索设备名称、IP 或标签"><button class="ghost">设备组⌄</button><button class="ghost">状态⌄</button></div>${table()}<p class="muted">显示 1–8，共 16 台</p></div>`,
apps:()=>`<div class="page-head"><div><h2>应用健康</h2><span class="muted">从应用视角定位版本漂移、CrashLoop 与跨设备故障。</span></div></div><div class="stats">${stat('LPK 应用','28','全 Fleet')}${stat('运行正常','24','85.7%','green')}${stat('Degraded','3','需要关注','amber')}${stat('Critical','1','健康检查失败','red')}${stat('版本漂移','4','跨设备版本不一致','amber')}</div><div class="card"><h2>应用矩阵</h2><p class="muted">每个方格代表一台设备上的应用实例</p>${table([['相册','16 台设备','3.9.1','14 正常 · 2 异常','Warning'],['影视','8 台设备','2.6.0','8 正常','Healthy'],['Hermes Studio','4 台设备','2026.08','3 正常 · 1 异常','Critical'],['文件服务','16 台设备','4.8.2','16 正常','Healthy'],['备份中心','12 台设备','1.8.4','11 正常 · 1 停止','Warning']])}</div>`,
storage:()=>`<div class="page-head"><div><h2>Fleet 存储健康</h2><span class="muted">按数据风险和预计写满时间排序，不让平均值掩盖热点。</span></div></div><div class="stats">${stat('物理磁盘','42','NVMe 18 · SATA 20')}${stat('总容量','126 TB','已用 84.6 TB')}${stat('Critical','2','需要立即处理','red')}${stat('30 天内写满','3','最短 6 天','amber')}${stat('Missing','1','USB 设备消失','red')}</div><div class="two"><div class="card"><h2>存储风险优先级</h2>${table([['猫盒-01 / System Pool','6.5 / 7.3 TB','89%','立即备份','Critical'],['猫盒-03 / Data Pool','10.8 / 12 TB','90%','6 天写满','Warning'],['猫盒-14 / USB Backup','—','设备消失','检查连接','Critical'],['猫盒-07 / Data Pool','5.4 / 6 TB','90%','18 天写满','Warning'],['猫盒-12 / Media Pool','7.2 / 10 TB','72%','126 天','Healthy']])}</div><div class="card"><h2>容量增长</h2><p class="muted">Fleet 总量 · 最近 30 天</p>${stat('当前','84.6 TB','30 天增长 +12.6 TB','amber')}<svg viewBox="0 0 320 160" width="100%"><path d="M0 135C60 130 80 105 130 110S210 70 250 77S285 40 320 30" fill="none" stroke="#2563eb" stroke-width="4"/></svg></div></div>`,
alerts:()=>`<div class="page-head"><div><h2>告警中心</h2><span class="muted">优先处理数据安全、服务不可用和持续资源压力。</span></div></div><div class="two"><div class="card alert-list"><div class="filters"><input placeholder="搜索设备、资源或告警"></div>${[['猫盒-01','nvme0n1 Media Errors 增加','3 分钟前','Critical'],['猫盒-07','相册健康检查失败','8 分钟前','Critical'],['猫盒-03','Data Pool 预计 6 天写满','12 分钟前','Warning'],['猫盒-12','到 Hub 丢包率 4.2%','18 分钟前','Warning'],['猫盒-14','USB Backup 设备消失','31 分钟前','Warning']].map((x,i)=>`<div class="risk ${i?'':'selected'}"><b>${x[0]} ${pill(x[3])}<span>${x[2]}</span></b><p>${x[1]}</p></div>`).join('')}</div><div class="card"><h2>nvme0n1 Media Errors 增加</h2><p>${pill('Critical')} · Firing · 未确认</p><button>确认并创建任务</button><h3>判断依据</h3><p>Media and Data Integrity Errors</p><p class="muted">当前值 2 · 过去 24 小时新增 2<br>阈值：增长 &gt; 0</p><h3>证据与时间线</h3><div class="code">10:42:18  SMART 采集发现 Media Errors = 2\n10:44:51  Collector 再次确认异常仍存在\n10:45:02  建议：立即备份并安排更换</div></div></div>`,
inspections:()=>`<div class="page-head"><div><h2>巡检报告 #2026-0823-1048</h2><span class="muted">执行时间 2026-08-23 10:48 · 耗时 3 分 42 秒 · Collector v1.0.0</span></div><button>导出 PDF 报告</button></div><div class="stats">${stat('巡检设备','16','全部设备')}${stat('通过','11','68.8%','green')}${stat('Warning','3','18.8%','amber')}${stat('Critical','1','需要立即处理','red')}${stat('Offline','1','未能完成巡检')}</div><div class="two"><div class="card"><h2>检查结果</h2>${[['设备可用性','15 / 16 通过'],['系统资源','14 / 16 通过'],['文件系统与 Btrfs','13 / 16 通过'],['物理磁盘与 SMART','1 Critical · 1 Restricted'],['LPK 应用','2 异常'],['网络连通性','1 Warning']].map(x=>`<div class="risk"><b>${x[0]}<span>${x[1]} ›</span></b></div>`).join('')}</div><div class="card"><h2>猫盒-01 / nvme0n1</h2><p>${pill('Critical')} NVMe Media Errors</p><div class="code">critical_warning : 0x04\nmedia_errors     : 2\npercentage_used  : 38%\navailable_spare  : 100%</div><p class="red"><b>建议：立即备份并安排更换 NVMe</b></p></div></div>`,
settings:()=>`<div class="page-head"><div><h2>设置</h2><span class="muted">管理 Collector 接入、认证、设备分组和告警策略。</span></div></div><div class="tabbar"><span class="tab active">设备接入</span><span class="tab">设备组与标签</span><span class="tab">告警阈值</span><span class="tab">通知渠道</span><span class="tab">数据保留</span></div><div class="card"><h2>接入新设备</h2><p class="muted">在目标 LazyCat 安装 Collector LPK，然后使用一次性配对码完成认证。</p><div class="steps">${[['1','安装 Collector','在目标设备安装只读 Collector LPK。'],['2','输入配对码','配对码有效期 10 分钟，仅可使用一次。'],['3','验证能力','自动检查 Host、LazyCat API、SMART 与 Runtime 权限。'],['4','分配设备组','设置位置、标签和告警策略。']].map(x=>`<div class="card step"><b>${x[0]}</b><h3>${x[1]}</h3><p class="muted">${x[2]}</p></div>`).join('')}</div><div class="card" style="margin-top:18px"><span class="muted">一次性配对码</span><h1 style="letter-spacing:5px">LZC-9H2K-7Q4M</h1><button id="copy">复制</button></div></div>`};
const titles={overview:['Fleet Overview','全部设备 · 实时健康与风险'],devices:['设备','16 台设备 · 4 个设备组'],apps:['应用','跨设备查看 LPK 健康、版本与资源异常'],storage:['存储健康','容量、Btrfs、SMART 与物理磁盘风险'],alerts:['告警','根因聚合、确认、静默与恢复'],inspections:['巡检报告','Fleet 全量巡检 · 固定快照与原始证据'],settings:['设置','设备接入、分组、阈值与通知']};
function render(key){document.querySelector('#nav').innerHTML=navs.map(n=>`<button class="nav-item ${n[0]===key?'active':''}" data-page="${n[0]}"><span>${n[1]}</span>${n[2]}</button>`).join('');document.querySelector('#title').textContent=titles[key][0];document.querySelector('#subtitle').textContent=titles[key][1];document.querySelector('#content').innerHTML=pages[key]();location.hash=key;document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>render(x.dataset.page));const c=document.querySelector('#copy');if(c)c.onclick=()=>{navigator.clipboard?.writeText('LZC-9H2K-7Q4M');toast('配对码已复制')};}
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}document.querySelector('#inspect').onclick=()=>toast('已创建 Fleet 全量巡检任务');render(pages[location.hash.slice(1)]?location.hash.slice(1):'overview');
